version: '3'
services:
  nginx:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./dist:/var/www/html/:Z
  
  php:
    build:
      context: docker
      dockerfile: php/Dockerfile
    networks: 
      - internal
    volumes:
      - ./dist:/var/www/html:Z
      - ./docker/php/data:/var/www/data:Z

  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    networks: 
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: harmonie

  adminer:
    image: adminer
    restart: always
    networks: 
      - internal
    ports:
      - 8081:8080

networks:
  internal:
    driver: bridge
